
# https://zensical.org/docs/setup/basics/?h=theme#theme-variant
#variant = "classic"

# https://zensical.org/docs/setup/language/
language = "en"

# Zensical provides a number of feature toggles that change the behavior
# of the documentation site.
features = [
    # https://zensical.org/docs/setup/header/#announcement-bar
    "announce.dismiss",

    # https://zensical.org/docs/setup/repository/#code-actions
    "content.action.edit",

    # https://zensical.org/docs/setup/repository/#code-actions
    #"content.action.view",

    # https://zensical.org/docs/authoring/code-blocks/#code-annotations
    "content.code.annotate",

    # https://zensical.org/docs/authoring/code-blocks/#code-copy-button
    "content.code.copy",

    # https://zensical.org/docs/authoring/code-blocks/#code-selection-button
    #"content.code.select",

    # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
    "content.footnote.tooltips",

    # https://zensical.org/docs/authoring/content-tabs/#linked-content-tabs
    "content.tabs.link",

    # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
    "content.tooltips",

    # https://zensical.org/docs/setup/header/#automatic-hiding
    # "header.autohide",

    # https://zensical.org/docs/setup/navigation/#navigation-expansion
    # "navigation.expand",

    # https://zensical.org/docs/setup/footer/#navigation
    "navigation.footer",

    # https://zensical.org/docs/setup/navigation/#section-index-pages
    "navigation.indexes",

    # https://zensical.org/docs/setup/navigation/#instant-navigation
    "navigation.instant",

    # https://zensical.org/docs/setup/navigation/#instant-prefetching
    "navigation.instant.prefetch",

    # https://zensical.org/docs/setup/navigation/#progress-indicator
    #"navigation.instant.progress",

    # When navigation paths are activated, a breadcrumb navigation is rendered
    # above the title of each page
    # https://zensical.org/docs/setup/navigation/#navigation-path
    "navigation.path",

    # When pruning is enabled, only the visible navigation items are included
    # in the rendered HTML, reducing the size of the built site by 33% or more.
    # https://zensical.org/docs/setup/navigation/#navigation-pruning
    #"navigation.prune",

    # When tabs are enabled, top-level sections are rendered in a menu layer
    # below the header for viewports above 1220px, but remain as-is on mobile.
    # https://zensical.org/docs/setup/navigation/#navigation-tabs
    #"navigation.tabs",

    # When sticky tabs are enabled, navigation tabs will lock below the header
    # and always remain visible when scrolling down.
    # https://zensical.org/docs/setup/navigation/#sticky-navigation-tabs
    #"navigation.tabs.sticky",

    # A back-to-top button can be shown when the user, after scrolling down,
    # starts to scroll up again.
    # https://zensical.org/docs/setup/navigation/#back-to-top-button
    "navigation.top",

    # When anchor tracking is enabled, the URL in the address bar is
    # automatically updated with the active anchor as highlighted in the table
    # of contents.
    # https://zensical.org/docs/setup/navigation/#anchor-tracking
    "navigation.tracking",

    # When search highlighting is enabled and a user clicks on a search result,
    # Zensical will highlight all occurrences after following the link.
    # https://zensical.org/docs/setup/search/#search-highlighting
    "search.highlight",

    # When anchor following for the table of contents is enabled, the sidebar
    # is automatically scrolled so that the active anchor is always visible.
    # https://zensical.org/docs/setup/navigation/#anchor-following
    # "toc.follow",

    # When navigation integration for the table of contents is enabled, it is
    # always rendered as part of the navigation sidebar on the left.
    # https://zensical.org/docs/setup/navigation/#navigation-integration
    "toc.integrate",

    # When sections are enabled, top-level sections are rendered as groups in
    # the sidebar for viewports above 1220px, but remain as-is on mobile.
    # https://zensical.org/docs/setup/navigation/#navigation-sections
    "navigation.sections",

]

[project.theme]
custom_dir = "overrides"

# This was used for MkDocs
# site_dir = "site"

site_url = "https://menzzana.github.io/NAISS-support-web/"
repo_url = "https://github.com/menzzana/NAISS-support-web"
edit_uri = "blob/main/docs/"

[project]
site_name = "NAISS High Performance Computing"
docs_dir = "docs"
auto_nav = false

nav = [
  { "Home" = "index.md"},
  { "Requesting resources" = [
    { "Getting Access" = "getting_access/get_access.md" },
    { "Software Development Assistance" = "getting_access/dev_support.md" } ,
  ]},
  { "Dardel" = [
    { "Quick Start" = "dardel/basics/quickstart.md" },
    { "Introduction" = "dardel/basics/introduction.md" },
    { "How to Login" = [
       { "How to log in with SSH keys" = "dardel/login/ssh_login.md" },
       { "Generating SSH keys" = "dardel/login/ssh_keys.md" },
       { "How to log in with kerberos" = "dardel/login/kerberos_login.md" },
       { "How to login from Linux" = "dardel/login/linux_login.md" },
       { "How to login from Windows" = "dardel/login/windows_login.md" },
       { "How to login from Mac OS" = "dardel/login/mac_login.md" },
       { "How to access to Nvidia login node" = "dardel/login/nvidia_login.md" },
       { "How to configure kerberos and SSH" = "dardel/login/configuration.md" },
       { "How to reset your password" = "dardel/login/reset_password.md" },
       { "Interactive HPC on Dardel" = "dardel/login/interactive_hpc.md" },
       { "Mounting Dardel directories on your computer" = "dardel/login/mounting.md" },
     ]},
    { "How to Run Jobs" = [
       { "How to Run Jobs" = "dardel/run_jobs/job_scheduling.md" },
       { "How to submit jobs" = "dardel/run_jobs/queueing_jobs.md" },
       { "Job scripts" = "dardel/run_jobs/job_scripts.md" },
       { "Job script examples" = "dardel/run_jobs/job_scripts_dardel.md" },
       { "Job arrays" = "dardel/run_jobs/job_arrays.md" },
       { "Short jobs" = "dardel/run_jobs/short_jobs.md" },
       { "Run interactively" = "dardel/run_jobs/run_interactively.md" },
       { "Job Statistics" = "dardel/run_jobs/job_statistics.md" },
     ]},
    { "Data Management" = [
       { "Data Management" = "dardel/data_management/data_management.md" },
       { "Klemming" = "dardel/data_management/klemming.md" },
       { "Swestore" = "dardel/data_management/file_transfer_swestore-dcache.md" },
       { "File transfer" = "dardel/data_management/file_transfer.md" },
       { "KTH OneDrive (rclone)" = "dardel/data_management/rclone_onedrive.md" },
     ]},
    { "Frequently Asked Questions (FAQ)" = [
       { "FAQ" = "dardel/faq/faq.md" },
     ]},
  ]},
  { "Contact Support" = "contact/contact_support.md" },
  { "Available software" = [
    { "Available softwares" = "applications/index.md" },
    { "How to use module to load different softwares into your environment" = "dardel/software/module.md" },
  ]}
]

